//////////////////////////////////////////////////////////////
//                                                          //
// This testbench has been generated by the Verilog         //
// testbench generator                .                     //
// Copyright (c) 2012-2022 EDAUtils LLP                 //
// Contact help@edautils.com  for support/info.//
//                                                          //
//                                                          //
//////////////////////////////////////////////////////////////
//
//
// Generated by : protim on 10/16/24, 5:21 PM
//
//
module testbench;
	reg [0:60] indata_array;
	wire bench_sys_rst;
	wire bench_wbs_clk_i;
	wire [19:1]bench_wbs_adr_i;
	wire [15:0]bench_wbs_dat_i;
	wire [15:0]bench_wbs_dat_o;
	wire [1:0]bench_wbs_sel_i;
	wire bench_wbs_tga_i;
	wire bench_wbs_stb_i;
	wire bench_wbs_cyc_i;
	wire bench_wbs_we_i;
	wire bench_wbs_ack_o;
	wire bench_wbm_clk_i;
	wire [19:1]bench_wbm_adr_o;
	wire [15:0]bench_wbm_dat_o;
	wire [15:0]bench_wbm_dat_i;
	wire [1:0]bench_wbm_sel_o;
	wire bench_wbm_tga_o;
	wire bench_wbm_stb_o;
	wire bench_wbm_cyc_o;
	wire bench_wbm_we_o;
	wire bench_wbm_ack_i;



	assign bench_sys_rst = indata_array[0:0];
	assign bench_wbs_clk_i = indata_array[1:1];
	assign bench_wbs_adr_i = indata_array[2:20];
	assign bench_wbs_dat_i = indata_array[21:36];
	assign bench_wbs_sel_i = indata_array[37:38];
	assign bench_wbs_tga_i = indata_array[39:39];
	assign bench_wbs_stb_i = indata_array[40:40];
	assign bench_wbs_cyc_i = indata_array[41:41];
	assign bench_wbs_we_i = indata_array[42:42];
	assign bench_wbm_clk_i = indata_array[43:43];
	assign bench_wbm_dat_i = indata_array[44:59];
	assign bench_wbm_ack_i = indata_array[60:60];

	always
	begin
		#5  indata_array = $random;
	end

	wb_abrg inst(
        .sys_rst(bench_sys_rst), 
        .wbs_clk_i(bench_wbs_clk_i), 
        .wbs_adr_i(bench_wbs_adr_i), 
        .wbs_dat_i(bench_wbs_dat_i), 
        .wbs_dat_o(bench_wbs_dat_o), 
        .wbs_sel_i(bench_wbs_sel_i), 
        .wbs_tga_i(bench_wbs_tga_i), 
        .wbs_stb_i(bench_wbs_stb_i), 
        .wbs_cyc_i(bench_wbs_cyc_i), 
        .wbs_we_i(bench_wbs_we_i), 
        .wbs_ack_o(bench_wbs_ack_o), 
        .wbm_clk_i(bench_wbm_clk_i), 
        .wbm_adr_o(bench_wbm_adr_o), 
        .wbm_dat_o(bench_wbm_dat_o), 
        .wbm_dat_i(bench_wbm_dat_i), 
        .wbm_sel_o(bench_wbm_sel_o), 
        .wbm_tga_o(bench_wbm_tga_o), 
        .wbm_stb_o(bench_wbm_stb_o), 
        .wbm_cyc_o(bench_wbm_cyc_o), 
        .wbm_we_o(bench_wbm_we_o), 
        .wbm_ack_i(bench_wbm_ack_i)
    );

	initial
	begin
		$monitor($time, " sys_rst = %b , wbs_clk_i = %b , wbs_adr_i = %b , wbs_dat_i = %b , wbs_sel_i = %b , wbs_tga_i = %b , wbs_stb_i = %b , wbs_cyc_i = %b , wbs_we_i = %b , wbm_clk_i = %b , wbm_dat_i = %b , wbm_ack_i = %b , wbs_dat_o = %b , wbs_ack_o = %b , wbm_adr_o = %b , wbm_dat_o = %b , wbm_sel_o = %b , wbm_tga_o = %b , wbm_stb_o = %b , wbm_cyc_o = %b , wbm_we_o = %b  ",
			bench_sys_rst, bench_wbs_clk_i, bench_wbs_adr_i, bench_wbs_dat_i, bench_wbs_sel_i, bench_wbs_tga_i, bench_wbs_stb_i, bench_wbs_cyc_i, bench_wbs_we_i, bench_wbm_clk_i, bench_wbm_dat_i, bench_wbm_ack_i, bench_wbs_dat_o, bench_wbs_ack_o, bench_wbm_adr_o, bench_wbm_dat_o, bench_wbm_sel_o, bench_wbm_tga_o, bench_wbm_stb_o, bench_wbm_cyc_o, bench_wbm_we_o);
	end

	initial
	begin
		#500 $finish;
	end

endmodule
